### ISSUE TITLE
Limit in validMentionOrList

### ISSUE THREAD

**Issue by ricardozd** [kylemcc/twitter-text-go#2]
Hi,

In GoFoodie we are testing your library, we have a little problem with the limit of mention because we are parsing the users_ids and not the simple string ( nick )

Example:

user_id = @hffre4dQpgWZaAgejlJeXvyk6m75
nick =@fakeuser
 
validMentionOrList = regexp.MustCompile(`(?i)([^a-zA-Z0-9_!#$%&*` + atSignChars + `]|^|^\s*RT:?)([` + atSignChars + `]+)([a-z0-9_]{1,20})(/[a-z][a-z0-9_-]{0,24})?`)

Why there is this limit ( {1,20} )?

Thanks

**Comment by kylemcc** [comment]
Hi - that limit is related to the maximum length of a Twitter username. The same limit appears in the official Twitter text parsing libraries ([see here](https://github.com/twitter/twitter-text/blob/master/rb/lib/twitter-text/regex.rb#L157)). It seems like you're attempting to use this library to parse twitter-style usernames without the same limit. If so, feel free to fork this library and remove or extend the limit.

**Comment by ricardozd** [comment]
Thanks
